/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "ParameterMapUI.h"
#include "MainViewComponent.h"

//==============================================================================
/**
*/
class ChuckRacksAudioProcessorEditor  : public AudioProcessorEditor,
                                        public ButtonListener,
                                        public Timer,
                                        Slider::Listener
{
public:
    ChuckRacksAudioProcessorEditor (ChuckRacksAudioProcessor* ownerFilter);
    ~ChuckRacksAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g) override;
    void resized() override;
    
    ChuckRacksAudioProcessor * getProcessor() const
    {
        return static_cast<ChuckRacksAudioProcessor *>(getAudioProcessor());
        
    }
    
    void buttonClicked(Button* buttonThatWasPressed) override;
    String lastFileLoaded;
    
    void timerCallback() override;
    void sliderValueChanged (Slider* slider) override;
    
    
private:
    ScopedPointer<DrawableButton> addAllShredsButton;
    ScopedPointer<DrawableButton> removeAllShredsButton;
    ScopedPointer<DrawableButton> addNewFileContainerButton;
    ScopedPointer<DrawableButton> openParameterListButton;
    
    //ScopedPointer<TextButton> addAllShredsButton;
    ScopedPointer<TextButton> browseCodeButton;
    //ScopedPointer<TextButton> removeShredButton;
    //ScopedPointer<TextButton> addFileContainerButton;
    
    MainViewComponent mainView;
};


#endif  // PLUGINEDITOR_H_INCLUDED
