/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class ChuckPluginTest4AudioProcessorEditor  : public AudioProcessorEditor, public ButtonListener
{
public:
    ChuckPluginTest4AudioProcessorEditor (ChuckPluginTest4AudioProcessor* ownerFilter);
    ~ChuckPluginTest4AudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    ChuckPluginTest4AudioProcessor * getProcessor() const
    {
        return static_cast<ChuckPluginTest4AudioProcessor *>(getAudioProcessor());
        
    }
    ScopedPointer<TextButton> addShredButton;
    ScopedPointer<TextButton> browseCodeButton;
    ScopedPointer<TextButton> removeShredButton;
    void buttonClicked(Button* buttonThatWasPressed);
    String lastFileLoaded;
    
};


#endif  // PLUGINEDITOR_H_INCLUDED
